---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 794661109164834817-5gsrrfqXcZiYBEZJsvr7Ndn3cx7ltXJ
:access_token_secret: Hbpr4WW06BmDaCPzyUScJLZn1WCjFw8eeVfHtjT8wB40W
